- name: Basic installations for nodes
  hosts: k8nodes
  become: true
  tasks:
    # install required packages
    - include_tasks: "../../tasks/pkgs_worker-{{ ansible_distribution }}.yml"

    # br_netfilter and containerd
    - include_tasks: ../../tasks/setup_common.yml

    # kubelet service override
    - include_tasks: ../../tasks/kubelet_common.yml

  handlers:
    - import_tasks: ../../handlers/common.yml
