- name: Basic installations for nodes
  hosts: k8nodes
  become: true
  tasks:
    - name: Install k8s utility for nodes
      pacman:
        name:
        - kubelet
        - kube-proxy
        - kubectl
      state: present
      update_cache: yes