- name: Set up Kubernetes control plane
  hosts: k8control_primary

  tasks:
    # install required packages
    - include_tasks: "control_plane_setup_tasks-{{ ansible_distribution }}.yml"

    - name: Enable and load br_netfilter kernel module
      community.general.modprobe:
        name: br_netfilter
        state: present
        persistent: present
      become: true

    - name: Enable containerd and kubelet
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - containerd
        - kubelet
      become: true

    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest

    - name: Initialize the Kubernetes control plane
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 # Flannel 
      when: not kube_apiserver_manifest.stat.exists
      become: true

    - name: Wait for Kubernetes API server to be alive
      uri:
        url: https://localhost:6443/livez
        validate_certs: false
        method: GET
        status_code: 200
      register: result
      retries: 10
      delay: 10
      until: result.status == 200

    # Following three tasks need to be done as per https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
    - name: Create .kube directory
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory

    - name: Check if kubeconfig exists
      stat:
        path: "{{ ansible_env.HOME }}/.kube/config"
      register: kubeconfig

    - name: Copy kubeconfig to user directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      become: true
      when: not kubeconfig.stat.exists

    - name: Set kubeconfig file mode
      file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        mode: 0600

    - name: Install Flannel CNI
      command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
      when: not kube_apiserver_manifest.stat.exists
