- name: Remove iptables
  pacman:
    name: iptables
    extra_args: "--cascade"
    state: absent
- name: Install required packages
  pacman:
    name:
      - iproute2
      - iptables-nft
      - containerd
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true
  become: true
