- name: Set up Kubernetes control plane
  hosts: k8control
  become: true

  tasks:
    # install required packages
    - include_tasks: "control_plane_setup_tasks-{{ ansible_distribution }}.yml"

    - name: Enable containerd and kubelet
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - containerd
        - kubelet

    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest

      # TODO: As far as i understood we have to look into flanel for CIDR
    - name: Initialize the Kubernetes control plane
      command: kubeadm init --pod-network-cidr=
      when: not kube_apiserver_manifest.stat.exists
    
