- name: Basic installations for nodes
  hosts: k8nodes
  become: true
  tasks:
    - name: Remove iptables (conflicts with iptables-nft)
      pacman:
        name: iptables
        extra_args: "--cascade"
        state: absent
    - name: Install containerd and Kubernetes utility
      pacman:
        name:
          - iptables-nft
          - iproute2
          - containerd
          - kubelet
          - kube-proxy
          - kubeadm
        state: present
        update_cache: yes

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: true
        state: started
    
    - name: Enable kubelet (start will happen by kubeadm)
      systemd:
        name: kubelet
        enabled: true
