# playbooks using this must also have `handlers:` with `- import_tasks: handlers/common.yml`

- name: Check whether containerd config exists
  stat:
    path: /etc/containerd/config.toml
  register: containerd_config

- name: Create default containerd config
  block:
    - name: Create /etc/containerd
      file:
        path: /etc/containerd
        state: directory
    - name: Obtain containerd default config
      shell: containerd config default > /etc/containerd/config.toml
  when: not containerd_config.stat.exists
  become: true

# Followed installation guide tbh
- name: use systemd as cgroup driver
  lineinfile:
    dest: /etc/containerd/config.toml
    regexp: '(\s+SystemdCgroup) = false'
    line: '\1 = true'
    backrefs: yes
    state: present
  become: true

- name: Set sandbox_image to same version
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*sandbox_image\s*=).*'
    line: '\1 "registry.k8s.io/pause:3.10"'
    backrefs: yes
    state: present
  become: true
  notify:
    - Restart containerd


- name: enable containerd
  service:
    name: containerd
    enabled: yes

- name: Restart containerd if needed
  meta: flush_handlers
