- name: Remove iptables (conflicts with iptables-nft)
  pacman:
    name: iptables
    extra_args: "--cascade"
    state: absent

- name: Install required packages
  pacman:
    name:
      - iproute2
      - iptables-nft
      - containerd
      - cni-plugins
      - kubelet
      - kubeadm
    state: present
    update_cache: true
  become: true
