# For clarification purposes the shell installation script sets the location and the check for the binary was taken from there -> {HELM_INSTALL_DIR:="/usr/local/bin"}
- name: Install Helm on Kubernetes on control plane
  hosts: k8control_primary

  tasks:
    - name: Check if Helm is already installed
      stat:
        path: /usr/local/bin/helm
      register: helm_bin

    - name: Install Helm
      when: not helm_bin.stat.exists
      block:
        - name: Download Helm install script
          get_url:
            url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
            dest: /tmp/get_helm.sh
            mode: 0700

        - name: Run Helm install script
          command: /tmp/get_helm.sh

        - name: Verify Helm installation
          stat:
            path: /usr/local/bin/helm
          register: helm_bin_2
          changed_when: false
          failed_when: not helm_bin_2.stat.exists

        - name: Delete Helm install script
          file:
            path: /tmp/get_helm.sh
            state: absent

    - name: Install Helm diff plugin
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
