- name: Set up Kubernetes control plane
  hosts: k8control_primary
  vars:
    kube_path: "{{ ansible_env.HOME }}/.kube"
    kubeadm_conf_path: "{{ kube_path }}/config"

  tasks:
    # install required packages
    - include_tasks: "../../tasks/control_plane_pkgs-{{ ansible_distribution }}.yml"

    # br_netfilter and containerd
    - include_tasks: ../../tasks/setup_common.yml

    # kubelet service override
    - include_tasks: ../../tasks/kubelet_common.yml

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: true
        state: started
      become: true

    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kube_apiserver_manifest
      become: true

    - name: stop kubelet
      service:
        name: kubelet
        state: stopped
      when: not kube_apiserver_manifest.stat.exists
      become: true

    - name: Initialize the Kubernetes control plane
      command: >
        kubeadm init
          --apiserver-advertise-address=10.89.1.1
          --pod-network-cidr=10.244.0.0/16
          --upload-certs
      when: not kube_apiserver_manifest.stat.exists
      become: true

    - name: Wait for Kubernetes API server to be alive
      uri:
        url: https://localhost:6443/livez
        validate_certs: false
        method: GET
        status_code: 200
      register: result
      retries: 10
      delay: 10
      until: result.status == 200

    # Following three tasks need to be done as per https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
    - name: Create .kube directory
      file:
        path: "{{ kube_path }}"
        state: directory

    - name: Copy kubeadm config to user directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ kubeadm_conf_path }}"
        remote_src: true
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      become: true

    - name: Set kubeconfig file mode
      file:
        path: "{{ kubeadm_conf_path }}"
        mode: 0600

    - name: Install Flannel CNI
      command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: "{{ kubeadm_conf_path }}"
      when: not kube_apiserver_manifest.stat.exists

    # Apparently need to be restarted again after cni is applied
    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: true
      become: true

    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: true
      become: true
      
  handlers:
    - import_tasks: ../../handlers/common.yml
