# do not manage these!
dev:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
    deeb-laptop:
      ansible_host: 10.89.3.101
    deeb-desktop:
      ansible_host: 10.89.3.102
    andi-laptop:
      ansible_host: 10.89.3.1

distro_debian:
  hosts:
    alfred:
      ansible_host: 10.89.1.1

distro_arch:
  hosts:
    deebbox:
      ansible_host: 10.89.2.1
    deebnode01:
      ansible_host: 10.89.2.101
    andinode01:
      ansible_host: 10.89.1.101

# kubernetes control plane
k8control_primary:
  hosts:
    alfred:
      ansible_host: 10.89.1.1

k8control_secondary:
  hosts:
    deebbox:
      ansible_host: 10.89.2.1
    # TODO: add additional control planes

# kubernetes nodes
k8nodes:
  hosts:
    # deneb
    deebnode01:
      ansible_host: 10.89.2.101
    # andi
    andinode01:
      ansible_host: 10.89.1.101
