# do not manage these!
dev:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
    deeb-laptop: 10.89.3.101
    deeb-desktop: 10.89.3.102
    andi-laptop: 10.89.3.1

k8control:

k8nodes:
