# do not manage these!
dev:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
    deeb-laptop: 10.89.3.101
    deeb-desktop: 10.89.3.102
    andi-laptop: 10.89.3.1

# kubernetes control plane
k8control:
  hosts:
    # deneb
    deebbox: 10.89.2.1
    # andi
    alfred: 10.89.1.1
k8control-debian:
  hosts:
    alfred: 10.89.1.1
k8control-arch:
  hosts:
    deebbox: 10.89.2.1

# kubernetes nodes
# all arch linux
k8nodes:
  hosts:
    # deneb
    deebnode01: 10.89.2.101
    # andi
    # (tba)
